fix(annotation-engine) use refForward in order to get back the canvas…
thetribeio/react-components pull request #14
Opened 2021-03-24 15:47 UTC by dimitrilahaye

… ref

2021-03-24 15:49 UTC, jvasseur commented on .eslintrc.js
> -        '@thetribe/eslint-config-react',
Pourquoi tu n'étend plus la conf eslint pour react ?

2021-03-24 15:50 UTC, jvasseur commented on src/annotation-engine/stories.tsx
> +    return <StyledAnnotationEngine height={height} width={width} {...args} ref={canvasRef} />;
Je trouve pas ça top niveau usabilité d'avoir un composant qui nécessite toujours d'avoir une ref en paramètre.

2021-03-24 15:50 UTC, dimitrilahaye commented on .eslintrc.js
> -        '@thetribe/eslint-config-react',
On a eu le même soucis avec Roadcare, on a dû revoir la façon avec laquelle on configurait eslint car prettier avait changé d'implémentation un truc comme ça

2021-03-24 15:51 UTC, dimitrilahaye commented on src/annotation-engine/stories.tsx
> +    return <StyledAnnotationEngine height={height} width={width} {...args} ref={canvasRef} />;
Je sais on peut en parler, il faut que je fasse du métier dans le canvas du composant. Je voyais pas d'autres façon de faire

2021-03-24 15:51 UTC, jvasseur commented on .eslintrc.js
> -        '@thetribe/eslint-config-react',
Ouais mais ça veut dire que tu ne va plus respecter les standards de theTribe vu que tu n'inclus plus la config ESLint qui correspond.

2021-03-24 15:52 UTC, avarennes approved these changes, later dismissed

2021-03-24 15:53 UTC, jvasseur commented on src/annotation-engine/stories.tsx
> +    return <StyledAnnotationEngine height={height} width={width} {...args} ref={canvasRef} />;
Non mais le fait que tu **puisse** passer une ref est une bonne chose, ce qui n'est pas normal c'est qu'il soit **obligatoire** de passer une ref pour que le composant marche.

2021-03-24 15:54 UTC, avarennes commented on src/annotation-engine/stories.tsx
> +    return <StyledAnnotationEngine height={height} width={width} {...args} ref={canvasRef} />;
On peut peut-être se dire s'il y a pas de ref on fait un useRef ? @dimitrilahaye

2021-03-24 15:55 UTC, dimitrilahaye commented on src/annotation-engine/stories.tsx
> +    return <StyledAnnotationEngine height={height} width={width} {...args} ref={canvasRef} />;
ah oui ok, donc je dois catcher le cas où ya null et alors, je créer mon useRef comme c'était fait avant, c'est ça ?

2021-03-24 15:55 UTC, avarennes commented on src/annotation-engine/stories.tsx
> +    return <StyledAnnotationEngine height={height} width={width} {...args} ref={canvasRef} />;
yep j'imagine que se serait encore mieux comme ça... :-)

2021-03-24 16:02 UTC, jvasseur commented on src/annotation-engine/index.tsx
> +        const cRef = useRef(null);
```suggestion
        const cRef = useRef<HTMLCanvasElement>(null);
```
Maybe ?

2021-03-24 16:04 UTC, dimitrilahaye commented on src/annotation-engine/index.tsx
> +        const cRef = useRef(null);
ah bah oui, il gueulait pas donc j'ai pas fais gaffe !

2021-03-24 16:05 UTC, jvasseur submitted a review, later dismissed

2021-03-24 16:07 UTC, avarennes submitted a review, later dismissed

2021-03-25 10:26 UTC, avarennes approved these changes, later dismissed

2021-03-25 10:27 UTC, jvasseur requested changes

2021-03-25 10:27 UTC, jvasseur commented on src/annotation-engine/stories.tsx
> +        console.info('canvasRef', canvasRef);
A retirer non ?

2021-03-25 10:27 UTC, dimitrilahaye commented on src/annotation-engine/stories.tsx
> +        console.info('canvasRef', canvasRef);
punaise XD

2021-03-25 10:40 UTC, jvasseur approved these changes, later dismissed

2021-03-25 10:45 UTC, avarennes approved these changes

2021-03-25 10:46 UTC, merged